app = "vendex"
primary_region = "ams"

[build]

[env]
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start = true
  auto_stop = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
